const headerData = {
  'first':[
    {
      id: 1,
      label: "驾驶员",
      prop: "driver_name",
      width: "130",
      align: "center",
      signIndex: 0,
      sortable: false,
    },
    {
      id: 2,
      label: "自编号",
      prop: "v_num",
      width: "130",
      align: "center",
      signIndex: 1,
      sortable: true,
    },
    {
      id: 3,
      label: "车牌号", 
      prop: "lp_num",
      width: "130",
      align: "center",
      signIndex: 2,
      sortable: true,
    },
    {
      id: 4,
      label: "所属组织",
      prop: "group_name",
      width: "165",
      align: "center",
      signIndex: 3,
      sortable: true,
    },
    {
      id: 5,
      label: "日期",
      prop: "d_violation_date",
      width: "130",
      align: "center",
      signIndex: 4,
      sortable: true,
    },
    {
      id: 6,
      label: "来源",
      prop: "source_name",
      width: "130",
      align: "center",
      signIndex: 5,
      sortable: false,
    },
    {
      id: 7,
      label: "违规项目",
      prop: "violation_item_name",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: false,
    },{
      id: 8,
      label: "处罚依据",
      prop: "check_item",
      width: "130",
      align: "center",
      signIndex: 7,
      sortable: false,
    },
    {
      id: 9,
      label: "奖罚金额",
      prop: "check_amount",
      width: "130",
      align: "center",
      signIndex: 8,
      sortable: true,
    },
    {
      id: 10,
      label: "加减分数",
      prop: "check_core",
      width: "160",
      align: "center",
      signIndex: 9,
      sortable: true,
    }
  ],
  'second':[
    {
      id: 1,
      label: "驾驶员",
      prop: "driver_name",
      width: "130",
      align: "center",
      signIndex: 0,
      sortable: true,
    },{
      id: 2,
      label: "工单类型",
      prop: "order_type_name",
      width: "130",
      align: "center",
      signIndex: 1,
      sortable: false,
    },{
      id: 3,
      label: "事发时间",
      prop: "call_time",
      width: "130",
      align: "center",
      signIndex: 2,
      sortable: false,
    },{
      id: 4,
      label: "车牌号",
      prop: "lincense_plate_number",
      width: "165",
      align: "center",
      signIndex: 3,
      sortable: false,
    },{
      id: 5,
      label: "线路",
      prop: "line_name",
      width: "130",
      align: "center",
      signIndex: 4,
      sortable: false,
    },{
      id: 6,
      label: "事件简述",
      prop: "order_content",
      width: "130",
      align: "center",
      signIndex: 5,
      sortable: true,
    },{
      id: 7,
      label: "调查结果",
      prop: "result",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: true,
    },{
      id: 8,
      label: "是否有责",
      prop: "duty_name",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: true,
    },{
      id: 9,
      label: "处罚依据",
      prop: "punish_str",
      width: "160",
      align: "center",
      signIndex: 8,
      sortable: true,
    },{
      id: 10,
      label: "奖罚金额",
      prop: "fee",
      width: "160",
      align: "center",
      signIndex: 9,
      sortable: true,
    },{
      id: 11,
      label: "加减分数",
      prop: "score",
      width: "130",
      align: "center",
      signIndex: 10,
      sortable: true,
    }
  ],
  'third':[{
    id: 1,
    label: "驾驶员",
    prop: "driver_name",
    width: "130",
    align: "center",
    signIndex: 0,
    sortable: true,
  },
  {
    id: 2,
    label: "自编号",
    prop: "vehicle_number",
    width: "130",
    align: "center",
    signIndex: 1,
    sortable: false,
  },
  {
    id: 3,
    label: "车牌号", 
    prop: "lincense_plate_number",
    width: "130",
    align: "center",
    signIndex: 2,
    sortable: false,
  },
  {
    id: 4,
    label: "所属组织",
    prop: "department_name",
    width: "165",
    align: "center",
    signIndex: 3,
    sortable: true,
  },
  {
    id: 5,
    label: "线路",
    prop: "line",
    width: "130",
    align: "center",
    signIndex: 4,
    sortable: true,
  },
  {
    id: 6,
    label: "违法日期",
    prop: "d_violation_date",
    width: "130",
    align: "center",
    signIndex: 5,
    sortable: false,
  },
  {
    id: 7,
    label: "违法地点",
    prop: "c_place",
    width: "160",
    align: "center",
    signIndex: 6,
    sortable: true,
  },{
    id: 8,
    label: "违法项目",
    prop: "violation_name",
    width: "160",
    align: "center",
    signIndex: 7,
    sortable: true,
  },{
    id: 9,
    label: "扣分",
    prop: "score",
    width: "130",
    align: "center",
    signIndex: 8,
    sortable: false,
  },{
    id: 10,
    label: "罚款",
    prop: "money",
    width: "130",
    align: "center",
    signIndex: 9,
    sortable: false,
  },{
    id: 11,
    label: "交警处理结果",
    prop: "state",
    width: "130",
    align: "center",
    signIndex: 10,
    sortable: false,
  },{
    id: 12,
    label: "备注",
    prop: "c_remark",
    width: "130",
    align: "center",
    signIndex: 11,
    sortable: false,
  }],
  'fourth':[{
    id: 1,
    label: "驾驶员",
    prop: "driver_name",
    width: "130",
    align: "center",
    signIndex: 0,
    sortable: true,
  },
  {
    id: 2,
    label: "自编号",
    prop: "vehicle_number",
    width: "130",
    align: "center",
    signIndex: 1,
    sortable: false,
  },
  {
    id: 3,
    label: "车牌号", 
    prop: "lincense_plate_number",
    width: "130",
    align: "center",
    signIndex: 2,
    sortable: false,
  },
  {
    id: 4,
    label: "所属组织",
    prop: "department_name",
    width: "165",
    align: "center",
    signIndex: 3,
    sortable: true,
  },
  {
    id: 5,
    label: "线路",
    prop: "line",
    width: "130",
    align: "center",
    signIndex: 4,
    sortable: true,
  },
  {
    id: 6,
    label: "事故发生时间",
    prop: "d_accident_date",
    width: "130",
    align: "center",
    signIndex: 5,
    sortable: false,
  },
  {
    id: 7,
    label: "事故责任",
    prop: "accident_duty",
    width: "160",
    align: "center",
    signIndex: 6,
    sortable: true,
  },{
    id: 8,
    label: "事故地点",
    prop: "c_accident_address",
    width: "160",
    align: "center",
    signIndex: 7,
    sortable: true,
  },{
    id: 9,
    label: "事故类别",
    prop: "accident_category",
    width: "130",
    align: "center",
    signIndex: 8,
    sortable: true,
  },{
    id: 10,
    label: "事故描述",
    prop: "c_describe",
    width: "130",
    align: "center",
    signIndex: 9,
    sortable: true,
  },{
    id: 11,
    label: "人伤金额",
    prop: "accident_total_fee",
    width: "130",
    align: "center",
    signIndex: 10,
    sortable: true,
  },{
    id: 12,
    label: "车辆维修金额",
    prop: "n_actual_fee",
    width: "150",
    align: "center",
    signIndex: 11,
    sortable: true,
  },{
    id: 13,
    label: "保险理赔金额",
    prop: "n_insurance_pay_fee",
    width: "150",
    align: "center",
    signIndex: 12,
    sortable: true,
  },{
    id: 14,
    label: "他人赔付金额",
    prop: "n_personal_fee",
    width: "150",
    align: "center",
    signIndex: 13,
    sortable: true,
  },{
    id: 15,
    label: "事故净损失",
    prop: "n_loss_fee",
    width: "150",
    align: "center",
    signIndex: 14,
    sortable: true,
  }],
  'fifth':[{
    id: 1,
    label: "姓名",
    prop: "driver_name",
    width: "120",
    align: "center",
    signIndex: 0,
  },
  {
    id: 2,
    label: "所属组织",
    prop: "dept_name",
    width: "150",
    align: "center",
    signIndex: 1,
  },
  {
    id: 3,
    label: "开始时间",
    prop: "start_date",
    width: "120",
    align: "center",
    signIndex: 2,
  },
  {
    id: 4,
    label: "结束时间",
    prop: "end_date",
    width: "120",
    align: "center",
    signIndex: 3,
  },
  {
    id: 5,
    label: "天数",
    prop: "leave_days",
    width: "80",
    align: "center",
    signIndex: 4,
  },
  {
    id: 6,
    label: "类型",
    prop: "leave_type_name",
    width: "100",
    align: "center",
    signIndex: 5,
  },
  {
    id: 7,
    label: "扣分",
    prop: "de_score",
    width: "80",
    align: "center",
    signIndex: 6,
  },
  {
    id: 8,
    label: "是否取消月考核",
    prop: "is_cancle_star_name",
    width: "120",
    align: "center",
    signIndex: 7,
  },
  {
    id: 9,
    label: "录入人",
    prop: "created_name",
    width: "100",
    align: "center",
    signIndex: 8,
  },
  {
    id: 10,
    label: "录入时间",
    prop: "created_date",
    width: "150",
    align: "center",
    signIndex: 9,
  }]
}

export default headerData