export default {
  data () {
    return {
      lineCustomSettingList: [
        {
          id: 1,
          label: "线路",
          prop: "Line",
          width: "200",
          align: "center",
          signIndex: 0,
          sortable: false,
        },
        {
          id: 2,
          label: "GPS里程(km)",
          prop: "gps_mile",
          width: "130",
          align: "center",
          signIndex: 1,
          sortable: true,
        },
        {
          id: 3,
          label: "营运里程(km)",
          prop: "operation_mile",
          width: "130",
          align: "center",
          signIndex: 2,
          sortable: true,
        },
        {
          id: 4,
          label: "普票金额",
          prop: "total_day_purchase",
          width: "130",
          align: "center",
          signIndex: 3,
          sortable: true,
        },
        {
          id: 5,
          label: "实体卡人次",
          prop: "PhysicalCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 4,
          sortable: false,
        },
        {
          id: 6,
          label: "实体卡金额",
          prop: "PhysicalCardAmount",
          width: "130",
          align: "center",
          signIndex: 5,
          sortable: false,
        },
        {
          id: 7,
          label: "支付宝人次",
          prop: "AlipayPersonCount",
          width: "130",
          align: "center",
          signIndex: 6,
          sortable: false,
        },
        {
          id: 8,
          label: "支付宝金额",
          prop: "AlipayAmount",
          width: "130",
          align: "center",
          signIndex: 7,
          sortable: false,
        },
        {
          id: 9,
          label: "银联乘车码人次",
          prop: "UnionPayCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 8,
          sortable: false,
        },
        {
          id: 10,
          label: "银联乘车码金额",
          prop: "UnionPayCodeAmount",
          width: "130",
          align: "center",
          signIndex: 9,
          sortable: false,
        },
        {
          id: 11,
          label: "银联卡人次",
          prop: "UnionPayCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 10,
          sortable: false,
        },
        {
          id: 12,
          label: "银联卡金额",
          prop: "UnionPayCardAmount",
          width: "130",
          align: "center",
          signIndex: 11,
          sortable: false,
        },
        {
          id: 13,
          label: "银联付款码人次",
          prop: "UnionPayPaymentCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 12,
          sortable: false,
        },
        {
          id: 14,
          label: "银联付款码金额",
          prop: "UnionPayPaymentCodeAmount",
          width: "130",
          align: "center",
          signIndex: 13,
          sortable: false,
        },
        {
          id: 15,
          label: "自发码人次",
          prop: "SelfIssuedCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 14,
          sortable: false,
        },
        {
          id: 16,
          label: "自发码金额",
          prop: "SelfIssuedCodeAmount",
          width: "130",
          align: "center",
          signIndex: 15,
          sortable: false,
        },
        {
          id: 17,
          label: "微信乘车码人次",
          prop: "WeChatCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 16,
          sortable: false,
        },
        {
          id: 18,
          label: "微信乘车码金额",
          prop: "WeChatCodeAmount",
          width: "130",
          align: "center",
          signIndex: 17,
          sortable: false,
        },
        {
          id: 19,
          label: "部标二维码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 18,
          sortable: false,
        },
        {
          id: 20,
          label: "部标二维码金额",
          prop: "StandardQRCodeAmount",
          width: "130",
          align: "center",
          signIndex: 19,
          sortable: false,
        },
        {
          id: 21,
          label: "军休码人次",
          prop: "MilitaryRetireeCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 20,
          sortable: false,
        },
        {
          id: 22,
          label: "献血荣誉码人次",
          prop: "BloodDonationHonorCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 21,
          sortable: false,
        },
        {
          id: 23,
          label: "浙里老兵码人次",
          prop: "ZheliVeteranCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 22,
          sortable: false,
        },
        {
          id: 24,
          label: "合计人次",
          prop: "TotalPersonCount",
          width: "130",
          align: "center",
          signIndex: 23,
          sortable: false,
        },
        {
          id: 25,
          label: "合计金额",
          prop: "TotalAmount",
          width: "130",
          align: "center",
          signIndex: 24,
          sortable: false,
        },
        // {
        //   id: 24,
        //   label: "操作",
        //   prop: "operation",
        //   width: "130",
        //   align: "center",
        //   signIndex: 23,
        //   sortable: false,
        // },
      ],
      vehCustomSettingList: [
        {
          id: 1,
          label: "自编号",
          prop: "vechile_number",
          width: "200",
          align: "center",
          signIndex: 0,
          sortable: false,
        },
        {
          id: 2,
          label: "车牌号",
          prop: "vehicle_name",
          width: "130",
          align: "center",
          signIndex: 1,
          sortable: true,
        },
        {
          id: 3,
          label: "分公司",
          prop: "BranchCompany",
          width: "130",
          align: "center",
          signIndex: 2,
          sortable: true,
        },
        {
          id: 4,
          label: "线路",
          prop: "Line",
          width: "130",
          align: "center",
          signIndex: 3,
          sortable: true,
        },
        {
          id: 5,
          label: "GPS里程(km)",
          prop: "gps_mile",
          width: "130",
          align: "center",
          signIndex: 4,
          sortable: true,
        },
        {
          id: 6,
          label: "营运里程(km)",
          prop: "operation_mile",
          width: "130",
          align: "center",
          signIndex: 5,
          sortable: true,
        },
        {
          id: 7,
          label: "普票金额",
          prop: "total_day_purchase",
          width: "130",
          align: "center",
          signIndex: 6,
          sortable: true,
        },
        {
          id: 8,
          label: "实体卡人次",
          prop: "PhysicalCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 7,
          sortable: false,
        },
        {
          id: 9,
          label: "实体卡金额",
          prop: "PhysicalCardAmount",
          width: "130",
          align: "center",
          signIndex: 8,
          sortable: false,
        },
        {
          id: 10,
          label: "支付宝人次",
          prop: "AlipayPersonCount",
          width: "130",
          align: "center",
          signIndex: 9,
          sortable: false,
        },
        {
          id: 11,
          label: "支付宝金额",
          prop: "AlipayAmount",
          width: "130",
          align: "center",
          signIndex: 10,
          sortable: false,
        },
        {
          id: 12,
          label: "银联乘车码人次",
          prop: "UnionPayCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 11,
          sortable: false,
        },
        {
          id: 13,
          label: "银联乘车码金额",
          prop: "UnionPayCodeAmount",
          width: "130",
          align: "center",
          signIndex: 12,
          sortable: false,
        },
        {
          id: 14,
          label: "银联卡人次",
          prop: "UnionPayCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 13,
          sortable: false,
        },
        {
          id: 15,
          label: "银联卡金额",
          prop: "UnionPayCardAmount",
          width: "130",
          align: "center",
          signIndex: 14,
          sortable: false,
        },
        {
          id: 16,
          label: "银联付款码人次",
          prop: "UnionPayPaymentCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 15,
          sortable: false,
        },
        {
          id: 17,
          label: "银联付款码金额",
          prop: "UnionPayPaymentCodeAmount",
          width: "130",
          align: "center",
          signIndex: 16,
          sortable: false,
        },
        {
          id: 18,
          label: "自发码人次",
          prop: "SelfIssuedCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 17,
          sortable: false,
        },
        {
          id: 19,
          label: "自发码金额",
          prop: "SelfIssuedCodeAmount",
          width: "130",
          align: "center",
          signIndex: 18,
          sortable: false,
        },
        {
          id: 20,
          label: "微信乘车码人次",
          prop: "WeChatCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 19,
          sortable: false,
        },
        {
          id: 21,
          label: "微信乘车码金额",
          prop: "WeChatCodeAmount",
          width: "130",
          align: "center",
          signIndex: 20,
          sortable: false,
        },
        {
          id: 22,
          label: "部标二维码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 21,
          sortable: false,
        },
        {
          id: 23,
          label: "部标二维码金额",
          prop: "StandardQRCodeAmount",
          width: "130",
          align: "center",
          signIndex: 22,
          sortable: false,
        },
        {
          id: 24,
          label: "军休码人次",
          prop: "MilitaryRetireeCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 23,
          sortable: false,
        },
        {
          id: 25,
          label: "献血荣誉码人次",
          prop: "BloodDonationHonorCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 24,
          sortable: false,
        },
        {
          id: 26,
          label: "嘉兴人才码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 25,
          sortable: false,
        },
        {
          id: 27,
          label: "浙里老兵码人次",
          prop: "ZheliVeteranCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 26,
          sortable: false,
        },
        {
          id: 28,
          label: "合计人次",
          prop: "TotalPersonCount",
          width: "130",
          align: "center",
          signIndex: 27,
          sortable: false,
        },
        {
          id: 29,
          label: "合计金额",
          prop: "TotalAmount",
          width: "130",
          align: "center",
          signIndex: 28,
          sortable: false,
        },
        // {
        //   id: 27,
        //   label: "操作",
        //   prop: "operation",
        //   width: "130",
        //   align: "center",
        //   signIndex: 26,
        //   sortable: false,
        // },
      ],
      deptCustomSettingList: [
        {
          id: 1,
          label: "分公司",
          prop: "BranchCompany",
          width: "200",
          align: "center",
          signIndex: 0,
          sortable: false,
        },
        {
          id: 2,
          label: "GPS里程(km)",
          prop: "gps_mile",
          width: "130",
          align: "center",
          signIndex: 1,
          sortable: true,
        },
        {
          id: 3,
          label: "营运里程(km)",
          prop: "operation_mile",
          width: "130",
          align: "center",
          signIndex: 2,
          sortable: true,
        },
        {
          id: 4,
          label: "普票金额",
          prop: "total_day_purchase",
          width: "130",
          align: "center",
          signIndex: 3,
          sortable: true,
        },
        {
          id: 5,
          label: "实体卡人次",
          prop: "PhysicalCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 4,
          sortable: false,
        },
        {
          id: 6,
          label: "实体卡金额",
          prop: "PhysicalCardAmount",
          width: "130",
          align: "center",
          signIndex: 5,
          sortable: false,
        },
        {
          id: 7,
          label: "支付宝人次",
          prop: "AlipayPersonCount",
          width: "130",
          align: "center",
          signIndex: 6,
          sortable: false,
        },
        {
          id: 8,
          label: "支付宝金额",
          prop: "AlipayAmount",
          width: "130",
          align: "center",
          signIndex: 7,
          sortable: false,
        },
        {
          id: 9,
          label: "银联乘车码人次",
          prop: "UnionPayCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 8,
          sortable: false,
        },
        {
          id: 10,
          label: "银联乘车码金额",
          prop: "UnionPayCodeAmount",
          width: "130",
          align: "center",
          signIndex: 9,
          sortable: false,
        },
        {
          id: 11,
          label: "银联卡人次",
          prop: "UnionPayCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 10,
          sortable: false,
        },
        {
          id: 12,
          label: "银联卡金额",
          prop: "UnionPayCardAmount",
          width: "130",
          align: "center",
          signIndex: 11,
          sortable: false,
        },
        {
          id: 13,
          label: "银联付款码人次",
          prop: "UnionPayPaymentCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 12,
          sortable: false,
        },
        {
          id: 14,
          label: "银联付款码金额",
          prop: "UnionPayPaymentCodeAmount",
          width: "130",
          align: "center",
          signIndex: 13,
          sortable: false,
        },
        {
          id: 15,
          label: "自发码人次",
          prop: "SelfIssuedCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 14,
          sortable: false,
        },
        {
          id: 16,
          label: "自发码金额",
          prop: "SelfIssuedCodeAmount",
          width: "130",
          align: "center",
          signIndex: 15,
          sortable: false,
        },
        {
          id: 17,
          label: "微信乘车码人次",
          prop: "WeChatCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 16,
          sortable: false,
        },
        {
          id: 18,
          label: "微信乘车码金额",
          prop: "WeChatCodeAmount",
          width: "130",
          align: "center",
          signIndex: 17,
          sortable: false,
        },
        {
          id: 19,
          label: "部标二维码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 18,
          sortable: false,
        },
        {
          id: 20,
          label: "部标二维码金额",
          prop: "StandardQRCodeAmount",
          width: "130",
          align: "center",
          signIndex: 19,
          sortable: false,
        },
        {
          id: 21,
          label: "军休码人次",
          prop: "MilitaryRetireeCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 20,
          sortable: false,
        },
        {
          id: 22,
          label: "献血荣誉码人次",
          prop: "BloodDonationHonorCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 21,
          sortable: false,
        },
        {
          id: 23,
          label: "浙里老兵码人次",
          prop: "ZheliVeteranCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 22,
          sortable: false,
        },
        {
          id: 24,
          label: "合计人次",
          prop: "TotalPersonCount",
          width: "130",
          align: "center",
          signIndex: 23,
          sortable: false,
        },
        {
          id: 25,
          label: "合计金额",
          prop: "TotalAmount",
          width: "130",
          align: "center",
          signIndex: 24,
          sortable: false,
        },
        // {
        //   id: 24,
        //   label: "操作",
        //   prop: "operation",
        //   width: "130",
        //   align: "center",
        //   signIndex: 23,
        //   sortable: false,
        // },
      ],
      driCustomSettingList: [
        {
          id: 1,
          label: "日期",
          prop: "Date",
          width: "200",
          align: "center",
          signIndex: 0,
          sortable: false,
        },
        {
          id: 2,
          label: "姓名",
          prop: "driver_name",
          width: "130",
          align: "center",
          signIndex: 1,
          sortable: true,
        },
        {
          id: 3,
          label: "工号",
          prop: "driver_code",
          width: "130",
          align: "center",
          signIndex: 2,
          sortable: true,
        },
        {
          id: 4,
          label: "分公司",
          prop: "BranchCompany",
          width: "130",
          align: "center",
          signIndex: 3,
          sortable: true,
        },
        {
          id: 5,
          label: "GPS里程(km)",
          prop: "gps_mile",
          width: "130",
          align: "center",
          signIndex: 4,
          sortable: true,
        },
        {
          id: 6,
          label: "营运里程(km)",
          prop: "operation_mile",
          width: "130",
          align: "center",
          signIndex: 5,
          sortable: true,
        },
        {
          id: 7,
          label: "普票金额",
          prop: "total_day_purchase",
          width: "130",
          align: "center",
          signIndex: 6,
          sortable: true,
        },
        {
          id: 8,
          label: "实体卡人次",
          prop: "PhysicalCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 7,
          sortable: false,
        },
        {
          id: 9,
          label: "实体卡金额",
          prop: "PhysicalCardAmount",
          width: "130",
          align: "center",
          signIndex: 8,
          sortable: false,
        },
        {
          id: 10,
          label: "支付宝人次",
          prop: "AlipayPersonCount",
          width: "130",
          align: "center",
          signIndex: 9,
          sortable: false,
        },
        {
          id: 11,
          label: "支付宝金额",
          prop: "AlipayAmount",
          width: "130",
          align: "center",
          signIndex: 10,
          sortable: false,
        },
        {
          id: 12,
          label: "银联乘车码人次",
          prop: "UnionPayCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 11,
          sortable: false,
        },
        {
          id: 13,
          label: "银联乘车码金额",
          prop: "UnionPayCodeAmount",
          width: "130",
          align: "center",
          signIndex: 12,
          sortable: false,
        },
        {
          id: 14,
          label: "银联卡人次",
          prop: "UnionPayCardPersonCount",
          width: "130",
          align: "center",
          signIndex: 13,
          sortable: false,
        },
        {
          id: 15,
          label: "银联卡金额",
          prop: "UnionPayCardAmount",
          width: "130",
          align: "center",
          signIndex: 14,
          sortable: false,
        },
        {
          id: 16,
          label: "银联付款码人次",
          prop: "UnionPayPaymentCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 15,
          sortable: false,
        },
        {
          id: 17,
          label: "银联付款码金额",
          prop: "UnionPayPaymentCodeAmount",
          width: "130",
          align: "center",
          signIndex: 16,
          sortable: false,
        },
        {
          id: 18,
          label: "自发码人次",
          prop: "SelfIssuedCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 17,
          sortable: false,
        },
        {
          id: 19,
          label: "自发码金额",
          prop: "SelfIssuedCodeAmount",
          width: "130",
          align: "center",
          signIndex: 18,
          sortable: false,
        },
        {
          id: 20,
          label: "微信乘车码人次",
          prop: "WeChatCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 19,
          sortable: false,
        },
        {
          id: 21,
          label: "微信乘车码金额",
          prop: "WeChatCodeAmount",
          width: "130",
          align: "center",
          signIndex: 20,
          sortable: false,
        },
        {
          id: 22,
          label: "部标二维码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 21,
          sortable: false,
        },
        {
          id: 23,
          label: "部标二维码金额",
          prop: "StandardQRCodeAmount",
          width: "130",
          align: "center",
          signIndex: 22,
          sortable: false,
        },
        {
          id: 24,
          label: "军休码人次",
          prop: "MilitaryRetireeCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 23,
          sortable: false,
        },
        {
          id: 25,
          label: "献血荣誉码人次",
          prop: "BloodDonationHonorCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 24,
          sortable: false,
        },
        {
          id: 26,
          label: "嘉兴人才码人次",
          prop: "StandardQRCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 25,
          sortable: false,
        },
        {
          id: 27,
          label: "浙里老兵码人次",
          prop: "ZheliVeteranCodePersonCount",
          width: "130",
          align: "center",
          signIndex: 26,
          sortable: false,
        },
        {
          id: 28,
          label: "合计人次",
          prop: "TotalPersonCount",
          width: "130",
          align: "center",
          signIndex: 27,
          sortable: false,
        },
        {
          id: 29,
          label: "合计金额",
          prop: "TotalAmount",
          width: "130",
          align: "center",
          signIndex: 28,
          sortable: false,
        },
        // {
        //   id: 27,
        //   label: "操作",
        //   prop: "operation",
        //   width: "130",
        //   align: "center",
        //   signIndex: 26,
        //   sortable: false,
        // },
      ],
      lineCumColumnIndex: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],
      vehCumColumnIndex: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
      deptCumColumnIndex: [2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25],
      driCumColumnIndex: [5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
      lineSumTotal: {
        2: '',3: '',4: '',5: '',6: '',7: '',8: '',9: '',10: '',11: '',12: '',13: '',14: '',
        15: '',16: '',17: '',18: '',19: '',20: '',21: '',22: '',23: '',24: '',25: ''
      },
      vehSumTotal: {
        5: '',6: '',7: '',8: '',9: '',10: '',11: '',12: '',13: '',14: '',15: '',16: '',17: '',
        18: '',19: '',20: '',21: '',22: '',23: '', 24: '',25: '',26: '', 27: '',28: '',29: ''
      },
      deptSumTotal: {
        2: '',3: '',4: '',5: '',6: '',7: '',8: '',9: '',10: '',11: '',12: '',13: '',14: '',
        15: '',16: '',17: '',18: '',19: '',20: '',21: '',22: '',23: '',24: '',25: ''
      },
      driSumTotal: {
        5: '',6: '',7: '',8: '',9: '',10: '',11: '',12: '',13: '',14: '',15: '',16: '',17: '',
        18: '',19: '',20: '',21: '',22: '',23: '', 24: '',25: '',26: '', 27: '',28: '',29: ''
      },
    }
  }
}