const headerData = {
  'peopleHurt':[
    {
      id: 1,
      label: "姓名",
      prop: "c_person_name",
      width: "130",
      align: "center",
      signIndex: 0,
      sortable: false,
    },
    {
      id: 2,
      label: "年龄",
      prop: "i_person_age",
      width: "130",
      align: "center",
      signIndex: 1,
      sortable: true,
    },
    {
      id: 3,
      label: "人员类型", //1对方 2己方
      prop: "person_type",
      width: "130",
      align: "center",
      signIndex: 2,
      sortable: false,
    },
    {
      id: 4,
      label: "身份证号",
      prop: "c_person_code",
      width: "165",
      align: "center",
      signIndex: 3,
      sortable: true,
    },
    {
      id: 5,
      label: "联系方式",
      prop: "c_person_phone",
      width: "130",
      align: "center",
      signIndex: 4,
      sortable: true,
    },
    {
      id: 6,
      label: "单位",
      prop: "c_work",
      width: "130",
      align: "center",
      signIndex: 5,
      sortable: false,
    },
    {
      id: 7,
      label: "住址",
      prop: "c_address",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: false,
    },{
      id: 8,
      label: "治疗医院",
      prop: "c_hospistal",
      width: "130",
      align: "center",
      signIndex: 7,
      sortable: false,
    },
    // {
    //   id: 9,
    //   label: "受损物品金额",
    //   prop: "n_good_fee",
    //   width: "160",
    //   align: "center",
    //   signIndex: 8,
    //   sortable: true,
    // },
    {
      id: 9,
      label: "伤情描述",
      prop: "c_describe",
      width: "130",
      align: "center",
      signIndex: 8,
      sortable: false,
    },
    {
      id: 10,
      label: "医疗费",
      prop: "n_medical_fee",
      width: "160",
      align: "center",
      signIndex: 9,
      sortable: true,
    },
    {
      id: 11,
      label: "误工费",
      prop: "n_missed_fee",
      width: "160",
      align: "center",
      signIndex: 10,
      sortable: true,
    },
    {
      id: 12,
      label: "护理费",
      prop: "n_nursing_fee",
      width: "160",
      align: "center",
      signIndex: 11,
      sortable: true,
    },
    {
      id: 13,
      label: "伙食费",
      prop: "n_food_fee",
      width: "160",
      align: "center",
      signIndex: 12,
      sortable: true,
    },
    {
      id: 14,
      label: "交通费",
      prop: "n_traffic_fee",
      width: "160",
      align: "center",
      signIndex: 13,
      sortable: true,
    },
  ],
  'carDamage':[
    {
      id: 1,
      label: "车牌号",
      prop: "c_vehicle_number",
      width: "130",
      align: "center",
      signIndex: 0,
      sortable: true,
    },{
      id: 2,
      label: "车辆区分",
      prop: "type",
      width: "130",
      align: "center",
      signIndex: 1,
      sortable: false,
    },{
      id: 3,
      label: "车辆类型",
      prop: "vehicle_type",
      width: "130",
      align: "center",
      signIndex: 2,
      sortable: false,
    },{
      id: 4,
      label: "车损程度",
      prop: "damage",
      width: "165",
      align: "center",
      signIndex: 3,
      sortable: false,
    },{
      id: 5,
      label: "驾驶员",
      prop: "c_driver_name",
      width: "130",
      align: "center",
      signIndex: 4,
      sortable: false,
    },{
      id: 6,
      label: "身份证",
      prop: "c_driver_code",
      width: "130",
      align: "center",
      signIndex: 5,
      sortable: true,
    },{
      id: 7,
      label: "联系方式",
      prop: "c_driver_phone",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: true,
    },{
      id: 8,
      label: "内部估价",
      prop: "n_inside_fee",
      width: "130",
      align: "center",
      signIndex: 6,
      sortable: true,
    },{
      id: 9,
      label: "保险公司估价",
      prop: "n_insurance_fee",
      width: "160",
      align: "center",
      signIndex: 8,
      sortable: true,
    },{
      id: 10,
      label: "评估中心估价",
      prop: "n_assessment_fee",
      width: "160",
      align: "center",
      signIndex: 9,
      sortable: true,
    },{
      id: 11,
      label: "实际费用",
      prop: "n_actual_fee",
      width: "130",
      align: "center",
      signIndex: 10,
      sortable: true,
    },{
      id: 12,
      label: "车损描述",
      prop: "c_describe",
      width: "130",
      align: "center",
      signIndex: 11,
      sortable: false,
    }
  ],
  'claimSettlement':[{
    id: 1,
    label: "关联保单号",
    prop: "insurance_code",
    width: "130",
    align: "center",
    signIndex: 0,
    sortable: true,
  },
  {
    id: 2,
    label: "保险公司",
    prop: "company",
    width: "130",
    align: "center",
    signIndex: 1,
    sortable: false,
  },
  {
    id: 3,
    label: "保险种类", 
    prop: "type_name",
    width: "130",
    align: "center",
    signIndex: 2,
    sortable: false,
  },
  {
    id: 4,
    label: "保险有效期",
    prop: "insurance_end",
    width: "165",
    align: "center",
    signIndex: 3,
    sortable: true,
  },
  {
    id: 5,
    label: "保单金额",
    prop: "insure_fee",
    width: "130",
    align: "center",
    signIndex: 4,
    sortable: true,
  },
  {
    id: 6,
    label: "理赔提交金额",
    prop: "actual_fee",
    width: "130",
    align: "center",
    signIndex: 5,
    sortable: false,
  },
  {
    id: 7,
    label: "理赔完成日期",
    prop: "finish_date",
    width: "160",
    align: "center",
    signIndex: 6,
    sortable: true,
  },{
    id: 8,
    label: "保险赔付金额",
    prop: "insurance_fee",
    width: "160",
    align: "center",
    signIndex: 7,
    sortable: true,
  },{
    id: 9,
    label: "理赔进度",
    prop: "state_name",
    width: "130",
    align: "center",
    signIndex: 8,
    sortable: false,
  },{
    id: 10,
    label: "备注",
    prop: "remark",
    width: "130",
    align: "center",
    signIndex: 9,
    sortable: false,
  }]
}

export default headerData