const headerData = {
  'first':[
    {
      id: 1,
      label: "线路",
      prop: "ex_line_name",
      width: "130",
      align: "center",
      signIndex: 0,
      sortable: false,
    },
    {
      id: 2,
      label: "大班工资（天/元）",
      prop: "bigFee",
      width: "130",
      align: "center",
      signIndex: 1,
      sortable: false,
    },
    {
      id: 3,
      label: "小班工资（天/元）",
      prop: "smallFee",
      width: "130",
      align: "center",
      signIndex: 2,
      sortable: false,
    },
    {
      id: 4,
      label: "操作",
      prop: "operation",
      width: "165",
      align: "center",
      signIndex: 3,
      sortable: false,
    }
  ],
  'second':[
    {
      id: 1,
      label: "线路",
      prop: "ex_line_name",
      width: "80",
      align: "center",
      signIndex: 0,
      sortable: false,
    },{
      id: 2,
      label: "综合奖金额（天/元）",
      prop: "comprehensiveAward",
      width: "600",
      align: "center",
      signIndex: 1,
      sortable: false,
    },
    {
      id: 3,
      label: "操作",
      prop: "operation",
      width: "140",
      align: "center",
      signIndex: 2,
      sortable: false,
    }
  ],
  'third':[{
    id: 1,
    label: "线路",
    prop: "ex_line_name",
    width: "130",
    align: "center",
    signIndex: 0,
    sortable: false,
  },
  {
    id: 2,
    label: "餐补金额（天/元）",
    prop: "fee",
    width: "130",
    align: "center",
    signIndex: 1,
    sortable: false,
  },
  {
    id: 3,
    label: "操作", 
    prop: "operation",
    width: "130",
    align: "center",
    signIndex: 2,
    sortable: false,
  }],
  'fourth':[{
    id: 1,
    label: "线路",
    prop: "ex_line_name",
    width: "130",
    align: "center",
    signIndex: 0,
    sortable: false,
  },
  {
    id: 2,
    label: "请假趟次金额（趟/元）",
    prop: "bigFee",
    width: "150",
    align: "center",
    signIndex: 1,
    sortable: false,
  },
  {
    id: 3,
    label: "临时请假趟次金额（趟/元）",
    prop: "smallFee",
    width: "180",
    align: "center",
    signIndex: 2,
    sortable: false,
  },
  {
    id: 4,
    label: "操作", 
    prop: "operation",
    width: "130",
    align: "center",
    signIndex: 3,
    sortable: false,
  }],
}

export default headerData