const flowChartListData = [
  {
    id: 1,
    title: '递交入党申请书',
    related_personnel:'群众',
    describe: '向工作、学习所在单位党组织提出入党申请；没有工作、学习单位或工作、学习单位未建立党组织的，向居住地党组织提出入党申请；流动人员还可以向单位所在地党组织或单位主管部门党组织、流动党员党组织提出入党申请',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 2,
    title: '党组织派人谈话',
    related_personnel:'群众',
    describe: '加强教育培养',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 3,
    title: '推荐和确定入党积极份子',
    related_personnel:'群众',
    describe: '入党申请人递交入党申请书六个月以上，具备入党积极分子条件，采取党员推荐、群团组织推优等方式产生人选，由支部委员会（不设支部委员会的由支部大会）研究决定，并报上级党委备案',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 4,
    title: '上级党委备案',
    related_personnel:'支委会（支部党员大会）',
    describe: '上级党委备案',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 5,
    title: '指定培养联系人',
    related_personnel:'2名培养联系人',
    describe: '指定1-2名正式党员作为入党积极分子的培养联系人。吸收入党积极分子听党课、参加党内有关活动、分配一定的社会工作以及集中培训等',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 6,
    title: '培养教育考察',
    related_personnel:'2名培养联系人',
    describe: '入党积极分子每季度向党组织汇报一次思想和工作情况；党组织对入党积极分子继续教育培养考察；培养联系人定期汇报入党积极分子情况',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 7,
    title: '确定发展对象',
    related_personnel:'支委会（支部党员大会）',
    describe: '听取党小组、培养联系人、党员和群众意见，支部委员会讨论同意，确定发展对象，并报上级党员备案',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 8,
    title: '报上级党委备案',
    related_personnel:'上级党委组织员',
    describe: '主要审查发展对象人选是否具备条件、手续是否完备。党委备案意见一般应书面通知党支部，上级党委备案同意的时候即为确定发展对象的时间',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 9,
    title: '确定入党介绍人',
    related_personnel:'2名正式党员',
    describe: '对发展对象进行教育培养考察',
    next_phase: '对发展对象进行政治审查，形成政治审查结论性材料。同本人谈话、查阅有关档案材料、找有关单位和人员了解情况以及必要的函调或外调。对流动人员中的发展对象进行政治审查时，还应当征求其户籍所在地和居住地基层党组织的意见',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 10,
    title: '开展集中培训',
    related_personnel:'基层党委或县级党委组织部门',
    describe: '对发展对象进行不少于3天或24学时的集中培训并进行测试',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 11,
    title: '进行政治审查',
    related_personnel:'所在支部2名正式党员',
    describe: '对发展对象进行政治审查，形成政治审查结论性材料。同本人谈话、查阅有关档案材料、找有关单位和人员了解情况以及必要的函调或外调。对流动人员中的发展对象进行政治审查时，还应当征求其户籍所在地和居住地基层党组织的意见',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 12,
    title: '支部委会审查',
    related_personnel:'支委会（支部党员大会）',
    describe: '进行政治审查。同本人谈话、查阅有关档案材料、找有关单位和人员了解情况以及必要的函调或外调。对流动人员中的发展对象进行政治审查时，还应当征求其户籍所在地和居住地基层党组织的意见',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 13,
    title: '上级党委预审',
    related_personnel:'上级党委组织员',
    describe: '审查发展对象条件、培养教育情况等；根据需要，听取执纪执法等部门意见。审查结果书面通知党支部；向审查合格的发展对象发放《中国共产党入党志愿书》',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 14,
    title: '填写入党志愿书',
    related_personnel:'预备党员',
    describe: '在入党介绍人指导下，由本人按照要求如实填写',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 15,
    title: '支部讨论大会',
    related_personnel:'支委会（支部党员大会）',
    describe: '发展对象汇报个人情况；入党介绍人介绍发展对象有关情况，表明意见；支部委员会报告审查情况；与会党员充分讨论、投票表决',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 16,
    title: '上级党委派人谈话',
    related_personnel:'上级党委委员或组织员',
    describe: '上级党委委员或组织员进一步了解并帮助发展对象提高对党的认识。谈话人应当将谈话情况和自己对发展对象能否入党的意见，如实填写在《入党共产党入党志愿书》上，并向党委汇报',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 17,
    title: '上级党委审批',
    related_personnel:'上级党委委员或组织员',
    describe: '上级党委委员或组织员集体讨论和表决，两个以上发展对象应当逐个审议和表决再上一级党委组织部门备案，审议和表决',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 18,
    title: '在上级党委组织部门备案',
    related_personnel:'上级党委委员或组织员',
    describe: '再上一级党委组织部门备案，审议和表决',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 19,
    title: '编入党支部和党小组',
    related_personnel:'基层党支部书记、副书记或组织委员',
    describe: '及时编入；继续进行教育和考察',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 20,
    title: '入党宣誓',
    related_personnel:'基层党委或党支部（党总支）',
    describe: '奏国歌；党组织负责同志致辞；预备党员宣誓；参加宣誓的预备党员代表发言；党组织负责同志讲话、提出要求',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 21,
    title: '继续教育考察',
    related_personnel:'基层党支部书记、副书记或组织委员',
    describe: '参加党的组织生活、听本人汇报、个别谈心、集中培训、实践锻炼等',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 22,
    title: '提出转正申请',
    related_personnel:'预备党员',
    describe: '预备期满，书面提出申请',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 23,
    title: '支部讨论大会',
    related_personnel:'支委会（支部党员大会）',
    describe: '党小组提出意见；党支部征求党员和群众的意见；支部委员会审查',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 24,
    title: '上级党委审批',
    related_personnel:'上级党委委员或组织员',
    describe: '审批结果及时通知党支部。党支部书记应当同本人谈话，并将审批结果在党员大会上宣布',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
  {
    id: 25,
    title: '材料归档',
    related_personnel:'正式党员',
    describe: '递交《中国共产党入党志愿书》、入党申请书、政治审查材料、转正申请书、培养教育考察材料。有人事档案的，存入本人人事档案；无人事档案的，建立党员档案，由所在党委或县级党委组织部门保存',
    next_phase: '',
    next_phase_related_personnel: '',
    next_phase_describe: '',
    is_pass: false,
  },
]

export default flowChartListData